### ISSUE TITLE
Update to include the new parser?

### ISSUE THREAD

**Issue by some16** [Daeik/obsidian-nomnoml-diagram#4]
On the Nomnoml website they are currently testing a new parser and it would be great if that could be added as feature.

**Comment by shemraz** [comment]
Bumping this, would love for it to be added too!

**Comment by Daeik** [comment]
Thanks to @grdmnt's PR(https://github.com/Daeik/obsidian-nomnoml-diagram/pull/5), the latest released version([v1.2.0](https://github.com/Daeik/obsidian-nomnoml-diagram/releases/tag/1.2.0)) includes the new parser(of nomnoml 1.6.2)!
